### ISSUE TITLE
BAN YEDİM

### ISSUE THREAD

**Issue by Kodikusik** [Teals53/CraftRiseHack#3]
EE BANLATTI CONFİG

**Comment by Teals53** [comment]
BANANE

**Comment by Kodikusik** [comment]
CONFİGİN BOZUQ

**Comment by Faysal1987** [comment]
ÇOK GÜZEL CONFİG İNDİRMEDİM AMA İÇ SEZİLERİM SÖYLEDİ SENİN AMINA KOYİM
